export const previewStorage = [
  {
    name: 'Sydney',
    bgi: 'Preview-images/Sydney_Opera_House_and_Harbour_Bridge_Dusk_(2)_2019-06-21.jpg',
    pri: 'Preview-images/Sydney_Opera_House_and_Harbour_Bridge_Dusk_(2)_2019-06-21.jpg',
    sbPara: "Travel spot: Sydney<br>Country: Australia<br>continent: Australia<br><a href=\"https://www.ixigo.com/search/result/flight?from=DEL&to=SYD&date=28122024&adults=1&children=0&infants=0&class=e&source=Search%20Form\" class=\"anch2\" >Flight(Delhi): 12hr30min</a>",
    parabody: "Sydney, capital of New South Wales and one of Australia's largest cities, is best known for its harbourfront Sydney Opera House, with a distinctive sail-like design. Massive Darling Harbour and Circular Quay are hubs of waterside life, with the towering, arched Harbour Bridge and esteemed Royal Botanic Garden nearby. Sydney Tower’s outdoor platform, the Skywalk, offers 360-degree views of the city and suburbs <a href=\"https://www.australia.com/en-in/places/sydney-and-surrounds/guide-to-sydney.html\" target=\"_blank\"><u>for more</u></a>",
  },
  {
    name: 'Melbourne',
    bgi: 'Preview-images/Melbourne_Skyline_and_Princes_Bridge_-_Dec_2008_(cropped).jpg',
    pri: 'Preview-images/Melbourne_Skyline_and_Princes_Bridge_-_Dec_2008_(cropped).jpg',
    sbPara: "Travel spot: Melbourne<br>Country: Australia<br>continent: Australia<br><a href=\"https://www.ixigo.com/search/result/flight?from=DEL&to=MEL&date=28122024&adults=1&children=0&infants=0&class=e&source=Search%20Form\" class=\"anch2\" >Flight(Delhi): 12hr45min</a>",
    parabody: "Melbourne, the coastal capital of the southeastern Australian state of Victoria, is known for its vibrant culture, arts, and coffee. The city is home to many of Australia's best-known landmarks, such as the Melbourne Cricket Ground, the National Gallery of Victoria, and the Royal Botanic Gardens. <a href=\"https://www.visitmelbourne.com/\" target=\"_blank\"><u>for more</u></a>",
  },
  {
    name: 'Queenstown',
    bgi: "Preview-images/QUEENStown.jpg",
    pri: "Preview-images/QUEENStown.jpg",
    sbPara: "Travel spot: Queenstown<br>Country: New Zealand<br>continent: Oceania<br><a href=\"https://www.ixigo.com/search/result/flight?from=DEL&to=ZQN&date=28122024&adults=1&children=0&infants=0&class=e&source=Search%20Form\" class=\"anch2\" >Flight(Delhi): 16hr30min</a>",
    parabody: "Queenstown, a resort town in Otago in the south-west of New Zealand's South Island, is built around an inlet called Queenstown Bay on Lake Wakatipu. It is known for its adventure sports, and is also a base for exploring the region’s vineyards and historic mining towns. <a href=\"https://www.newzealand.com/int/queenstown/\" target=\"_blank\"><u>for more</u></a>",
  },
  {
    name: 'Wellington',
    bgi: 'Preview-images/Wellington_city_with_Cable_Car_(cropped).jpg',
    pri: 'Preview-images/Wellington_city_with_Cable_Car_(cropped).jpg',
    sbPara: "Travel spot: Wellington<br>Country: New Zealand<br>continent: Oceania<br><a href=\"https://www.ixigo.com/search/result/flight?from=DEL&to=WLG&date=28122024&adults=1&children=0&infants=0&class=e&source=Search%20Form\" class=\"anch2\" >Flight(Delhi): 16hr45min</a>",
    parabody: "Wellington, the capital of New Zealand, sits near the North Island’s southernmost point on the Cook Strait. A compact city, it encompasses a waterfront promenade, sandy beaches, a working harbour and colourful timber houses on surrounding hills. <a href=\"https://www.wellingtonnz.com/\" target=\"_blank\"><u>for more</u></a>",
  },
  {
    name: 'TajMahal',
    bgi: 'Preview-images/Taj_Mahal_(Edited).jpeg',
    pri: 'Preview-images/Taj_Mahal_(Edited).jpeg',
    sbPara: "Travel spot: Taj Mahal<br>Country: India<br>continent: Asia<br><a href=\"https://www.ixigo.com/search/result/flight?from=DEL&to=AGR&date=28122024&adults=1&children=0&infants=0&class=e&source=Search%20Form\" class=\"anch2\" >Flight(Delhi): 1hr</a>",
    parabody: "The Taj Mahal, an ivory-white marble mausoleum on the southern bank of the river Yamuna in the Indian city of Agra, was commissioned in 1632 by the Mughal emperor Shah Jahan to house the tomb of his favourite wife, Mumtaz Mahal. <a href=\"https://www.tajmahal.gov.in/\" target=\"_blank\"><u>for more</u></a>",
  },
  {
    name: 'Paris',
    bgi: 'Preview-images/La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques,_Paris_août_2014_(2).jpg',
    pri: 'Preview-images/La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques,_Paris_août_2014_(2).jpg',
    sbPara: "Travel spot: Paris<br>Country: France<br>continent: Europe<br><a href=\"https://www.ixigo.com/search/result/flight?from=DEL&to=CDG&date=28122024&adults=1&children=0&infants=0&class=e&source=Search%20Form\" class=\"anch2\" >Flight(Delhi): 9hr30min</a>",
    parabody: "Paris, France's capital, is a major European city and a global center for art, fashion, gastronomy and culture. Its 19th-century cityscape is crisscrossed by wide boulevards and the River Seine. <a href=\"https://en.parisinfo.com/\" target=\"_blank\"><u>for more</u></a>",
  },
  {
    name: 'Dublin',
    bgi: 'Preview-images/Samuel_Beckett_Bridge_At_Sunset_Dublin_Ireland_(97037639)_(cropped).jpeg',
    pri: 'Preview-images/Samuel_Beckett_Bridge_At_Sunset_Dublin_Ireland_(97037639)_(cropped).jpeg',
    sbPara: "Travel spot: Dublin<br>Country: Ireland<br>continent: Europe<br><a href=\"https://www.ixigo.com/search/result/flight?from=DEL&to=DUB&date=28122024&adults=1&children=0&infants=0&class=e&source=Search%20Form\" class=\"anch2\" >Flight(Delhi): 10hr30min</a>",
    parabody: "Dublin, capital of the Republic of Ireland, is on Ireland’s east coast at the mouth of the River Liffey. Its historic buildings include Dublin Castle, dating to the 13th century, and imposing St Patrick’s Cathedral, founded in 1191. <a href=\"https://www.visitdublin.com/\" target=\"_blank\"><u>for more</u></a>",
  },
  {
    name: 'Maldives',
    bgi: 'Preview-images/Bathala_(Maldives)_8.jpeg',
    pri: 'Preview-images/Bathala_(Maldives)_8.jpeg',
    sbPara: "Travel spot: Maldives<br>Country: Maldives<br>continent: Asia<br><a href=\"https://www.ixigo.com/search/result/flight?from=DEL&to=MLE&date=28122024&adults=1&children=0&infants=0&class=e&source=Search%20Form\" class=\"anch2\" >Flight(Delhi): 5hr</a>",
    parabody: "The Maldives, officially the Republic of Maldives, is a small archipelagic state in South Asia, situated in the Indian Ocean. It lies southwest of Sri Lanka and India, about 700 kilometres from the Asian continent's mainland. <a href=\"https://www.visitmaldives.com/\" target=\"_blank\"><u>for more</u></a>",
  },
  {
    name: 'Leh(Ladakh)',
    bgi: 'Preview-images/Leh,_Old_city,_Ladakh,_India.jpg',
    pri: 'Preview-images/Leh,_Old_city,_Ladakh,_India.jpg',
    sbPara: "Travel spot: Leh(Ladakh)<br>Country: India<br>continent: Asia<br><a href=\"https://www.ixigo.com/search/result/flight?from=DEL&to=IXL&date=28122024&adults=1&children=0&infants=0&class=e&source=Search%20Form\" class=\"anch2\" >Flight(Delhi): 1hr30min</a>",
    parabody: "Leh, a high-desert city in the Himalayas, is the capital of the Leh region in northern India’s Jammu and Kashmir state. Originally a stop for trading caravans, Leh is now known for its Buddhist sites and nearby trekking areas. <a href=\"https://www.lehladakhindia.com/\" target=\"_blank\"><u>for more</u></a>",
  },
  {
    name: 'Amsterdam',
    bgi: 'Preview-images/KeizersgrachtReguliersgrachtAmsterdam.jpg',
    pri: 'Preview-images/KeizersgrachtReguliersgrachtAmsterdam.jpg',
    sbPara: "Travel spot: Amsterdam<br>Country: Netherlands<br>continent: Europe<br><a href=\"https://www.ixigo.com/search/result/flight?from=DEL&to=AMS&date=28122024&adults=1&children=0&infants=0&class=e&source=Search%20Form\" class=\"anch2\" >Flight(Delhi): 8hr30min</a>",
    parabody: "Amsterdam is the Netherlands’ capital, known for its artistic heritage, elaborate canal system and narrow houses with gabled facades, legacies of the city’s 17th-century Golden Age. <a href=\"https://www.iamsterdam.com/\" target=\"_blank\"><u>for more</u></a>",
  },
  {
    name: 'London',
    bgi: 'Preview-images/London_Skyline_(125508655).jpeg',
    pri: 'Preview-images/London_Skyline_(125508655).jpeg',
    sbPara: "Travel spot: London<br>Country: United Kingdom<br>continent: Europe<br><a href=\"https://www.ixigo.com/search/result/flight?from=DEL&to=LHR&date=28122024&adults=1&children=0&infants=0&class=e&source=Search%20Form\" class=\"anch2\" >Flight(Delhi): 9hr</a>",
    parabody: "London, the capital of England and the United Kingdom, is a 21st-century city with history stretching back to Roman times. At its centre stand the imposing Houses of Parliament, the iconic ‘Big Ben’ clock tower and Westminster Abbey, site of British monarch coronations. <a href=\"https://visitlondon.com/\" target=\"_blank\"><u>for more</u></a>",
  },
  {
    name: 'Azerbaijan',
    bgi: 'Preview-images/Budug_Azerbaijan16.jpg',
    pri: 'Preview-images/Budug_Azerbaijan16.jpg',
    sbPara: "Travel spot: Azerbaijan<br>Country: Azerbaijan<br>continent: Asia<br><a href=\"https://www.ixigo.com/search/result/flight?from=DEL&to=GYD&date=28122024&adults=1&children=0&infants=0&class=e&source=Search%20Form\" class=\"anch2\" >Flight(Delhi): 4hr30min</a>",
    parabody: "Azerbaijan, the Land of Fire, is a country in the South Caucasus region of Eurasia at the crossroads of Eastern Europe and Western Asia. It is bounded by the Caspian Sea to the east, Russia to the north, Georgia to the northwest, Armenia to the west and Iran to the south. <a href=\"https://azerbaijan.travel/\" target=\"_blank\"><u>for more</u></a>",
  }
];
